services:
  gym-app:
    build: .
    container_name: gym-app
    restart: unless-stopped
    ports:
      - "2222:8000"
    volumes:
      - /mnt/gym-app:/data
    environment:
      - GYM_DATA_DIR=/data
